//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocTap_DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyHocTapEntities : DbContext
    {
        public QuanLyHocTapEntities()
            : base("name=QuanLyHocTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Teaching> Teachings { get; set; }
    
        [DbFunction("QuanLyHocTapEntities", "FN_SCORE_STATISTICS_OVERTIME")]
        public virtual IQueryable<FN_SCORE_STATISTICS_OVERTIME_Result> FN_SCORE_STATISTICS_OVERTIME(Nullable<System.DateTime> sTART, Nullable<System.DateTime> fINISH)
        {
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var fINISHParameter = fINISH.HasValue ?
                new ObjectParameter("FINISH", fINISH) :
                new ObjectParameter("FINISH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_SCORE_STATISTICS_OVERTIME_Result>("[QuanLyHocTapEntities].[FN_SCORE_STATISTICS_OVERTIME](@START, @FINISH)", sTARTParameter, fINISHParameter);
        }
    }
}
