//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocTap_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int TeachingID { get; set; }
        public string StudentID { get; set; }
        public System.DateTime Registration_Date { get; set; }
        public Nullable<decimal> MidtermScore { get; set; }
        public Nullable<System.DateTime> ModifiedDateOfMidtermScore { get; set; }
        public Nullable<decimal> EndPointScore { get; set; }
        public Nullable<System.DateTime> ModifiedDateOfEndPointScore { get; set; }
    
        public virtual Teaching Teaching { get; set; }
        public virtual Student Student { get; set; }
    }
}
